const materials=[
 {name:'Noma / Chalk',collection:'Noma collection',type:'mineral',finish:'Honed',colour:'Warm white',description:'A quiet mineral surface with a soft, chalky depth. Designed to carry light across larger planes.',swatch:'one'},
 {name:'Alto / Ivory Vein',collection:'Alto collection',type:'veined',finish:'Satin',colour:'Ivory',description:'Subtle linear movement through an ivory field, for surfaces that reward a closer look.',swatch:'two'},
 {name:'Obsidian / Still',collection:'Obsidian collection',type:'textured',finish:'Matte',colour:'Graphite',description:'Deep, mineral and tactile. A grounding surface for hospitality and custom furniture.',swatch:'three'},
 {name:'Strata / Silt',collection:'Strata collection',type:'textured',finish:'Textured',colour:'Earth',description:'A layered, earth-toned texture inspired by sediment and slow geological time.',swatch:'four'},
 {name:'Lumen / Shell',collection:'Lumen collection',type:'translucent',finish:'Satin',colour:'Shell',description:'A luminous surface with a warm translucency for softly backlit architectural moments.',swatch:'five'},
 {name:'Obsidian / Coal',collection:'Obsidian collection',type:'mineral',finish:'Honed',colour:'Black',description:'A near-black mineral surface with a considered, light-absorbing presence.',swatch:'six'}
];
const grid=document.querySelector('#material-grid');
function renderMaterials(filter='all'){grid.innerHTML=materials.filter(m=>filter==='all'||m.type===filter).map((m,i)=>`<article class="material-card" data-index="${materials.indexOf(m)}" tabindex="0"><div class="swatch ${m.swatch}"></div><span class="card-hover">+</span><div class="card-info"><h3>${m.name}</h3><p>${m.collection}</p></div></article>`).join('');document.querySelectorAll('.material-card').forEach(card=>{card.addEventListener('click',()=>openModal(+card.dataset.index));card.addEventListener('keydown',e=>e.key==='Enter'&&openModal(+card.dataset.index))})}
renderMaterials();
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');btn.classList.add('active');renderMaterials(btn.dataset.filter)}));
const backdrop=document.querySelector('#modal-backdrop');
function openModal(index){const m=materials[index];document.querySelector('#modal-img').src=index===0||index===1?'assets/material-macro.png':'assets/hero-ace.png';document.querySelector('#modal-img').alt=m.name;document.querySelector('#modal-collection').textContent=m.collection;document.querySelector('#modal-name').textContent=m.name;document.querySelector('#modal-description').textContent=m.description;document.querySelector('#modal-finish').textContent=m.finish;document.querySelector('#modal-colour').textContent=m.colour;backdrop.classList.add('open');document.body.style.overflow='hidden'}
function closeModal(){backdrop.classList.remove('open');document.body.style.overflow=''}document.querySelector('.modal-close').addEventListener('click',closeModal);backdrop.addEventListener('click',e=>e.target===backdrop&&closeModal());document.addEventListener('keydown',e=>e.key==='Escape'&&closeModal());document.querySelector('#sample-button').addEventListener('click',()=>{closeModal();const toast=document.querySelector('#toast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2500)});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const menuToggle=document.querySelector('.menu-toggle');const mainNav=document.querySelector('.main-nav');menuToggle.addEventListener('click',()=>{const open=mainNav.classList.toggle('mobile-open');menuToggle.setAttribute('aria-expanded',open);menuToggle.setAttribute('aria-label',open?'Close navigation':'Open navigation')});mainNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{mainNav.classList.remove('mobile-open');menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Open navigation')}));
